name: Integration test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup
      run: ./update.sh

    - name: Run
      run: timeout 5 ./run.sh -e /bin/bash # This is a hack :-)